-- MySQL Script generated by MySQL Workbench
-- qui 27 jun 2024 16:35:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NULL,
  `tipo_cliente` ENUM('e', 'p') NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `func_responsavel` VARCHAR(45) NULL,
  `tb_cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_empresa`, `tb_cliente_id_cliente`),
  INDEX `fk_tb_empresa_tb_cliente1_idx` (`tb_cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_empresa_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id_cliente`)
    REFERENCES `mydb`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(45) NULL,
  `cpf_funcionario` VARCHAR(45) NULL,
  `senha_funcionario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `cnh` VARCHAR(45) NULL,
  `tb_cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_pessoa`, `tb_cliente_id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `cnh_UNIQUE` (`cnh` ASC) VISIBLE,
  INDEX `fk_tb_pessoa_tb_cliente_idx` (`tb_cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pessoa_tb_cliente`
    FOREIGN KEY (`tb_cliente_id_cliente`)
    REFERENCES `mydb`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_aluguel` (
  `id_aluguel` INT NOT NULL AUTO_INCREMENT,
  `data_aluguel` DATE NULL,
  `tb_funcionario_id_funcionario` INT NOT NULL,
  `tb_cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_aluguel`, `tb_funcionario_id_funcionario`, `tb_cliente_id_cliente`),
  UNIQUE INDEX `id_aluguel_UNIQUE` (`id_aluguel` ASC) VISIBLE,
  INDEX `fk_tb_aluguel_tb_funcionario1_idx` (`tb_funcionario_id_funcionario` ASC) VISIBLE,
  INDEX `fk_tb_aluguel_tb_cliente1_idx` (`tb_cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_aluguel_tb_funcionario1`
    FOREIGN KEY (`tb_funcionario_id_funcionario`)
    REFERENCES `mydb`.`tb_funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluguel_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id_cliente`)
    REFERENCES `mydb`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_veiculo` (
    `id_veiculo` int(11) NOT NULL AUTO_INCREMENT,
  `nome_veiculo` varchar(45) NOT NULL,
  `ano_veiculo` varchar(45) NOT NULL,
  `marca_veiculo` varchar(45) NOT NULL,
  `tipo_veiculo` enum('c','m') NOT NULL,
  `cor_veiculo` varchar(45) NOT NULL,
  `placa_veiculo` varchar(45) NOT NULL,
  `estado_veiculo` enum('a','d') NOT NULL,
  `motor_veiculo` varchar(45) NOT NULL,
  `km_rodados` varchar(45) NOT NULL,
  `descricao_veiculo` varchar(45) NOT NULL,
  `qtd_portas` enum('0','2','4') NOT NULL,
  `acordicinado_veiculo` enum('s','n') NOT NULL,
  `portamala_ veiculo` enum('s','n') NOT NULL,
  `tamaho_veiculo` enum('p','m','g') NOT NULL,
  `cambio_veiculo` enum('m','a') NOT NULL,
  `npassageiro_veiculo` enum('2','4','5','6','7') NOT NULL,
  PRIMARY KEY (`id_veiculo`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_enderecos` (
  `id_enderecos` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(45) NULL,
  `tb_cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_enderecos`, `tb_cliente_id_cliente`),
  INDEX `fk_tb_enderecos_tb_cliente1_idx` (`tb_cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_enderecos_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id_cliente`)
    REFERENCES `mydb`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_manutencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_manutencao` (
  `id_manutencao` INT NOT NULL AUTO_INCREMENT,
  `data_ida` DATE NULL,
  `data_prev_volta` DATE NULL,
  `tb_veiculo_id_veiculo` INT NOT NULL,
  PRIMARY KEY (`id_manutencao`, `tb_veiculo_id_veiculo`),
  INDEX `fk_tb_manutencao_tb_veiculo1_idx` (`tb_veiculo_id_veiculo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_manutencao_tb_veiculo1`
    FOREIGN KEY (`tb_veiculo_id_veiculo`)
    REFERENCES `mydb`.`tb_veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_devolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_devolucao` (
  `id_devolucao` INT NOT NULL AUTO_INCREMENT,
  `data_devolucao` DATE NULL,
  `km_rodados` VARCHAR(45) NULL,
  `valor_cobrado` VARCHAR(45) NULL,
  `tb_aluguel_id_aluguel` INT NOT NULL,
  PRIMARY KEY (`id_devolucao`, `tb_aluguel_id_aluguel`),
  INDEX `fk_tb_devolucao_tb_aluguel1_idx` (`tb_aluguel_id_aluguel` ASC) VISIBLE,
  CONSTRAINT `fk_tb_devolucao_tb_aluguel1`
    FOREIGN KEY (`tb_aluguel_id_aluguel`)
    REFERENCES `mydb`.`tb_aluguel` (`id_aluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_carro_aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_carro_aluguel` (
  `tb_veiculo_id_veiculo` INT NOT NULL,
  `tb_aluguel_id_aluguel` INT NOT NULL,
  PRIMARY KEY (`tb_veiculo_id_veiculo`, `tb_aluguel_id_aluguel`),
  INDEX `fk_tb_veiculo_has_tb_aluguel_tb_aluguel1_idx` (`tb_aluguel_id_aluguel` ASC) VISIBLE,
  INDEX `fk_tb_veiculo_has_tb_aluguel_tb_veiculo1_idx` (`tb_veiculo_id_veiculo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_veiculo_has_tb_aluguel_tb_veiculo1`
    FOREIGN KEY (`tb_veiculo_id_veiculo`)
    REFERENCES `mydb`.`tb_veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_veiculo_has_tb_aluguel_tb_aluguel1`
    FOREIGN KEY (`tb_aluguel_id_aluguel`)
    REFERENCES `mydb`.`tb_aluguel` (`id_aluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
